# Generated by Django 3.1.2 on 2020-11-25 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('barcode', models.PositiveIntegerField(unique=True)),
                ('wholesale_pricse', models.PositiveIntegerField()),
                ('retailer_pricse', models.PositiveIntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Khaata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credit', models.IntegerField(default=0)),
                ('credit_limit', models.IntegerField()),
                ('credit_warning', models.PositiveIntegerField()),
                ('cnic', models.PositiveIntegerField(blank=True, null=True)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('profit', models.FloatField(default=0)),
                ('buyername', models.CharField(max_length=50)),
                ('genrated_date', models.DateTimeField(default=datetime.datetime(2020, 11, 25, 20, 59, 5, 746400))),
                ('details', models.TextField()),
                ('khaata_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_App.khaata')),
            ],
            options={
                'ordering': ['-genrated_date'],
            },
        ),
    ]
