# Generated by Django 3.1.2 on 2020-11-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('buyername', models.CharField(max_length=50)),
                ('genrated_date', models.DateTimeField(auto_now=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('barcode', models.PositiveIntegerField(unique=True)),
                ('wholesale_pricse', models.PositiveIntegerField()),
                ('retailer_pricse', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Khaata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_limit', models.PositiveIntegerField()),
                ('max_limit', models.PositiveIntegerField()),
                ('cnic', models.PositiveIntegerField(blank=True, null=True)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
