# Generated by Django 3.1.2 on 2020-11-28 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cash_deposit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='cash_return',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_refunded_bill',
            field=models.CharField(default='Not Refunded', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 22, 15, 17, 700045)),
        ),
    ]
