# Generated by Django 3.1.2 on 2020-11-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='khaata_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store_App.khaata'),
            preserve_default=False,
        ),
    ]
