# Generated by Django 3.1.2 on 2020-11-29 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0002_auto_20201128_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='refunded_return',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 15, 45, 33, 169120)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_refunded_bill',
            field=models.BooleanField(default=False),
        ),
    ]
