# Generated by Django 3.1.2 on 2020-11-28 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0002_auto_20201125_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cash_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='cash_return',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 16, 47, 18, 292555)),
        ),
    ]
