# Generated by Django 3.1.2 on 2020-11-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0003_auto_20201107_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khaata',
            name='max_limit',
        ),
        migrations.RemoveField(
            model_name='khaata',
            name='min_limit',
        ),
        migrations.AddField(
            model_name='khaata',
            name='credit',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
