# Generated by Django 3.1.2 on 2020-11-29 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0004_auto_20201129_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 1, 16, 37, 426710)),
        ),
    ]
