# Generated by Django 3.1.2 on 2020-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0004_auto_20201108_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaata',
            name='credit_limit',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
