# Generated by Django 3.1.2 on 2020-12-03 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0005_auto_20201130_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 21, 32, 44, 128769)),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='wholesale_pricse',
            field=models.FloatField(),
        ),
    ]
