# Generated by Django 3.1.2 on 2020-11-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0005_khaata_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaata',
            name='credit_warning',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khaata',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
