# Generated by Django 3.1.2 on 2020-11-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0006_auto_20201109_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
