# Generated by Django 3.1.2 on 2020-12-04 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0006_auto_20201203_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 0, 27, 58, 266712)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='refunded_return',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
