# Generated by Django 3.1.2 on 2020-11-17 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0008_auto_20201117_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 20, 54, 28, 700910)),
        ),
    ]
