# Generated by Django 3.1.2 on 2020-11-24 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0009_auto_20201117_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['genrated_date']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='khaata',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='bill',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 20, 7, 33, 977240)),
        ),
    ]
