# Generated by Django 3.1.2 on 2020-11-25 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0010_auto_20201124_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-genrated_date']},
        ),
        migrations.AlterModelOptions(
            name='khaata',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 12, 24, 35, 821521)),
        ),
    ]
