# Generated by Django 3.1.2 on 2020-11-25 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0011_auto_20201125_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='genrated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 12, 30, 26, 858992)),
        ),
    ]
