# Generated by Django 3.1.2 on 2020-11-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store_App', '0007_item_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Transsaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transection', models.IntegerField()),
                ('Transaction_Message', models.TextField()),
                ('Credit_Before_Transaction', models.IntegerField()),
                ('Credit_After_Transaction', models.IntegerField()),
                ('Transection_Date', models.DateTimeField(auto_now=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
                ('Khaata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_App.khaata')),
            ],
        ),
    ]
