# Generated by Django 3.1.2 on 2020-11-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction', models.IntegerField(blank=True, default=0)),
                ('Transaction_Message', models.TextField(max_length=500, null=True)),
                ('Credit_Before_Transaction', models.IntegerField(blank=True, null=True)),
                ('Credit_After_Transaction', models.IntegerField(blank=True, null=True)),
                ('Transaction_Date', models.DateTimeField(auto_now=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
                ('Khaata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_App.khaata')),
            ],
        ),
    ]
