# Generated by Django 3.1.2 on 2020-11-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Message',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
