# Generated by Django 3.1.2 on 2020-11-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_App', '0011_auto_20201125_1224'),
        ('DataAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transsaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transection', models.IntegerField()),
                ('Transaction_Message', models.TextField(max_length=500, null=True)),
                ('Credit_Before_Transaction', models.IntegerField()),
                ('Credit_After_Transaction', models.IntegerField()),
                ('Transection_Date', models.DateTimeField(auto_now=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
                ('Khaata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_App.khaata')),
            ],
        ),
        migrations.DeleteModel(
            name='Credit_Transsaction',
        ),
    ]
