# Generated by Django 3.1.2 on 2020-12-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0002_auto_20201130_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Message',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
