# Generated by Django 3.1.2 on 2020-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0003_auto_20201125_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Credit_After_Transaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Credit_Before_Transaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
