# Generated by Django 3.1.2 on 2020-11-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0004_auto_20201125_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction',
            field=models.IntegerField(default='Payment Received', null=True),
        ),
    ]
